<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Story of the World | <?php echo $this->location->getName() ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h1>Story of the World | <?php echo $this->location->getName() ?></h1>
        
        <div class="description">
          <?php echo $this->location->getDescription() ?>
        </div>
        
        <div class="posts">
            
        </div>
    </body>
</html>
